@url_dev = http://localhost:3055/v1/api/product
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2Y5NThlYzMyZjZkZTMyNDFmYTMxNzMiLCJlbWFpbCI6Im5nb2NkdXkwOEBnbWFpbC5jb20iLCJpYXQiOjE3NDg5NDQxMTEsImV4cCI6MTc0OTExNjkxMX0.0958_q33J-v6XVvD-yCa8YJCpbPuycDJp8koq1y6Ct0
### get list cart user
POST {{url_dev}}/create
Content-Type: application/json
x-api-key: f470e0cf151674b21c7e373bfbb82dc807a9adf2c11a2c987bef31559fa49b9369856b2bfe4ec2eb8fd79b904afe2c1b469e6bb47ad6606a63e1e2c9be92456f
x-client-id: 67f958ec32f6de3241fa3173
authorization: {{jwt}}

{
  "product_name": "Áo sơ mi nam tay dài",
  "product_description": "High quality",
  "product_price": 100,
  "product_shop": "67f958ec32f6de3241fa3173",
  "product_type": "Clothing",
  "product_thumb": "product_thumb",
  "product_quantity": 100,
  "product_attributes": {
    "brand": "LV",
    "size": "M",
    "material": "denim"
  }
}


# @url_dev = http://localhost:3055/v1/api/product

### create product Electronics
POST {{url_dev}}/create
Content-Type: application/json
x-api-key: f470e0cf151674b21c7e373bfbb82dc807a9adf2c11a2c987bef31559fa49b9369856b2bfe4ec2eb8fd79b904afe2c1b469e6bb47ad6606a63e1e2c9be92456f
x-client-id: 67f958ec32f6de3241fa3173
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2Y5NThlYzMyZjZkZTMyNDFmYTMxNzMiLCJlbWFpbCI6Im5nb2NkdXkwOEBnbWFpbC5jb20iLCJpYXQiOjE3NDY2MDExNDksImV4cCI6MTc0Njc3Mzk0OX0.roJeyI9UGh2FVk13gbGfZv_IXYxawK9jGdxCivFQCOk

{
  "product_name": "Băng Quấn Bảo Vệ Khuỷu Tay Co Giãn Tốt Tiện Dụng Khi Chơi Thể Thao Cho Nam",
  "product_thumb": "https://salt.tikicdn.com/cache/100x100/ts/product/d6/4f/c3/71f089390f605d172b54edf6aaa1877e.jpg.webp",
  "product_description": "Áo thun nam MRM kiểu dáng Regular fit tôn dáng cơ thể, làm nổi bật form người mặc thêm nam tính, khỏe khoắn mà vẫn thoải mái vận động.",
  "product_price": 1234.000,
  "product_quantity": 23,
  "product_type": "Clothing",
  "product_attributes": {
    "brand": "MRM VietNam China",
    "size": "XL",
    "material": "Thun"
  }
}

### get all product drafts for shop
GET {{url_dev}}/drafts/all
Content-Type: application/json
x-api-key: f470e0cf151674b21c7e373bfbb82dc807a9adf2c11a2c987bef31559fa49b9369856b2bfe4ec2eb8fd79b904afe2c1b469e6bb47ad6606a63e1e2c9be92456f
x-client-id: 67f958ec32f6de3241fa3173
authorization: {{jwt}}

{
}

### get all product published for shop
GET {{url_dev}}/published/all
Content-Type: application/json
x-api-key: f470e0cf151674b21c7e373bfbb82dc807a9adf2c11a2c987bef31559fa49b9369856b2bfe4ec2eb8fd79b904afe2c1b469e6bb47ad6606a63e1e2c9be92456f
x-client-id: 67f958ec32f6de3241fa3173
authorization: {{jwt}}

{
}
### publish product for shop by id product
@id =683ad5235dc96e2a3c7e13de
POST {{url_dev}}/publish/{{id}}
Content-Type: application/json
x-api-key: f470e0cf151674b21c7e373bfbb82dc807a9adf2c11a2c987bef31559fa49b9369856b2bfe4ec2eb8fd79b904afe2c1b469e6bb47ad6606a63e1e2c9be92456f
x-client-id: 67f958ec32f6de3241fa3173
authorization: {{jwt}}

{
}

### Unpublish product for shop by id product
POST {{url_dev}}/unpublish/{{id}}
Content-Type: application/json
x-api-key: f470e0cf151674b21c7e373bfbb82dc807a9adf2c11a2c987bef31559fa49b9369856b2bfe4ec2eb8fd79b904afe2c1b469e6bb47ad6606a63e1e2c9be92456f
x-client-id: 67f958ec32f6de3241fa3173
authorization: {{jwt}}

{
}

### Search product by name
GET {{url_dev}}/search/bang quan
Content-Type: application/json
x-api-key: f470e0cf151674b21c7e373bfbb82dc807a9adf2c11a2c987bef31559fa49b9369856b2bfe4ec2eb8fd79b904afe2c1b469e6bb47ad6606a63e1e2c9be92456f

{
}

### get all product
GET {{url_dev}}
Content-Type: application/json
x-api-key: f470e0cf151674b21c7e373bfbb82dc807a9adf2c11a2c987bef31559fa49b9369856b2bfe4ec2eb8fd79b904afe2c1b469e6bb47ad6606a63e1e2c9be92456f

{
    "page": 1,
    "limit": 10
}

@product_id = 681b04efe1db8b3949b1aa12
### get product detail
GET {{url_dev}}/{{product_id}}
Content-Type: application/json
x-api-key: f470e0cf151674b21c7e373bfbb82dc807a9adf2c11a2c987bef31559fa49b9369856b2bfe4ec2eb8fd79b904afe2c1b469e6bb47ad6606a63e1e2c9be92456f

{

}

### update product
PATCH {{url_dev}}/{{product_id}}
Content-Type: application/json
x-api-key: f470e0cf151674b21c7e373bfbb82dc807a9adf2c11a2c987bef31559fa49b9369856b2bfe4ec2eb8fd79b904afe2c1b469e6bb47ad6606a63e1e2c9be92456f
x-client-id: 67f958ec32f6de3241fa3173
authorization: {{jwt}}

{
    "product_type": "Clothing",
    "product_attributes": {
      "brand": "MRM VietNam 0010"
    },
    "product_name": "Băng Quấn Bảo Vệ Khuỷu Tay Co Giãn Tốt Tiện Dụng Khi Chơi Thể Thao Cho Nam",
    "product_price": null
}